# Programación 201

Librerías científicas en Python: `Pandas`
------------------------------------------------------

### Ejercicio 1

Cargad los datos del fichero _got.csv_ en un _dataframe_. Este conjunto de datos recoge información de la [Guerra de los Cinco Reyes](https://awoiaf.westeros.org/index.php/War_of_the_Five_Kings) de las novelas de [Cancion de Hielo y Fuego](https://es.wikipedia.org/wiki/Canci%C3%B3n_de_hielo_y_fuego) de George R.R Martin.

Mostrad el número de filas del _dataframe_ y las etiquetas de los ejes.

In [19]:
# Respuesta

import pandas as pd
df= pd.read_csv("https://raw.githubusercontent.com/SebastianOberti/Bootcamp_DataScience_student/master/dataset/got.csv")
df.info()

pd.set_option("display.max_columns", 30)
df.columns
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                38 non-null     object
 1   year                38 non-null     int64
 2   battle_number       38 non-null     int64
 3   attacker_king       36 non-null     object
 4   defender_king       35 non-null     object
 5   attacker_1          38 non-null     object
 6   attacker_2          10 non-null     object
 7   attacker_3          3 non-null      object
 8   attacker_4          2 non-null      object
 9   defender_1          37 non-null     object
 10  defender_2          2 non-null      object
 11  defender_3          0 non-null      float64
 12  defender_4          0 non-null      float64
 13  attacker_outcome    37 non-null     object
 14  battle_type         37 non-null     object
 15  major_death         37 non-null     float64
 16  major_capture       37 non-null     float64
 17  attacker_size       24 non-null     float64
 18  defender_size       19 non-null     float64
 19  attacker_commander  37 non-null     object
 20  defender_commander  28 non-null     object
 21  summer              37 non-null     float64
 22  location            37 non-null     object
 23  region              38 non-null     object
 24  note                5 non-null      object
dtypes: float64(7), int64(2), object(16)
memory usage: 7.5+ KB

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,defender_2,defender_3,defender_4,attacker_outcome,battle_type,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,NaN,NaN,NaN,win,pitched battle,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,NaN,NaN,NaN,win,ambush,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN
2,Battle of Riverrun,298,3,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,NaN,NaN,NaN,win,pitched battle,0.0,1.0,15000.0,10000.0,"Jaime Lannister, Andros Brax","Edmure Tully, Tytos Blackwood",1.0,Riverrun,The Riverlands,NaN
3,Battle of the Green Fork,298,4,Robb Stark,Joffrey/Tommen Baratheon,Stark,NaN,NaN,NaN,Lannister,NaN,NaN,NaN,loss,pitched battle,1.0,1.0,18000.0,20000.0,"Roose Bolton, Wylis Manderly, Medger Cerwyn, H...","Tywin Lannister, Gregor Clegane, Kevan Lannist...",1.0,Green Fork,The Riverlands,NaN
4,Battle of the Whispering Wood,298,5,Robb Stark,Joffrey/Tommen Baratheon,Stark,Tully,NaN,NaN,Lannister,NaN,NaN,NaN,win,ambush,1.0,1.0,1875.0,6000.0,"Robb Stark, Brynden Tully",Jaime Lannister,1.0,Whispering Wood,The Riverlands,NaN

### Ejercicio 2

Agrupad los datos cargados en el ejercicio 1 por el principal bando atacante (*attacker\_1*). Para cada posición, mostrad el número de batallas y el resultado de la batalla (el resultado se encuentra en el campo *attacker\_outcome*).

In [20]:
# Respuesta

ej2 = df.groupby(['attacker_1', 'attacker_outcome'])['battle_number'].count()
ej2

attacker_1                   attacker_outcome
Baratheon                    loss                1
                             win                 4
Bolton                       win                 2
Bracken                      win                 1
Brave Companions             win                 1
Brotherhood without Banners  win                 1
Darry                        win                 1
Free folk                    loss                1
Frey                         win                 2
Greyjoy                      win                 7
Lannister                    loss                1
                             win                 7
Stark                        loss                2
                             win                 6
Name: battle_number, dtype: int64

### Ejercicio 3

Mostrad los datos de las batallas donde el numero de participantes supera los 15000 "hombres" (contando ambos bandos: *attacker\_size* y *defender\_size*), el resultado haya sido favorable para el atacante, y la batalla se haya producido en invierno (_summer=0_).

In [35]:
# Respuesta

df['both_sides'] = df['attacker_size'] + df['defender_size']

ej3 = df[(df['both_sides'] > 15000) & (df['summer'] == 0) & (df['attacker_outcome'] == 'win')]
ej3

#DUDA: que sucede con summer 1.0 es int o float? lo toma en un condicional siendo 1.0? en el CSV sale como int

Empty DataFrame
Columns: [name, year, battle_number, attacker_king, defender_king, attacker_1, attacker_2, attacker_3, attacker_4, defender_1, defender_2, defender_3, defender_4, attacker_outcome, battle_type, major_death, major_capture, attacker_size, defender_size, attacker_commander, defender_commander, summer, location, region, note, both_sides]
Index: []

### Ejercicio 4

Contad el número de lugares que aparecen más de una vez en _dataframe_ (campo _location_), utilizando las funciones de la librería _pandas_. ¿Existe algún lugar donde se haya realizado más de una batalla? Comprobad qué bandos estaban implicados.

In [107]:
# Respuesta

subset4 = df.groupby(['location']).size().to_frame(name = 'count_location').reset_index()
subset4

m4 = df.merge(subset4, how= 'left')\
            .filter(items=['location','count_location','attacker_1','defender_1'])\
            .sort_values(by=['location'])
m4f = m4[m4['count_location']>1]
m4f

            location  count_location attacker_1        defender_1
20             Darry             2.0      Darry         Lannister
6              Darry             2.0  Lannister             Darry
30    Deepwood Motte             2.0  Baratheon           Greyjoy
8     Deepwood Motte             2.0    Greyjoy             Stark
24         Harrenhal             2.0  Lannister  Brave Companions
17         Harrenhal             2.0      Stark         Lannister
7        Moat Cailin             2.0    Greyjoy             Stark
28       Moat Cailin             2.0     Bolton           Greyjoy
2           Riverrun             3.0  Lannister             Tully
5           Riverrun             3.0      Stark         Lannister
35          Riverrun             3.0  Lannister             Tully
15       Storm's End             2.0  Baratheon         Baratheon
33       Storm's End             2.0  Baratheon         Baratheon
12  Torrhen's Square             2.0    Greyjoy             Stark
10  Torrhen's Square             2.0      Stark           Greyjoy
13        Winterfell             3.0     Bolton             Stark
11        Winterfell             3.0    Greyjoy             Stark
37        Winterfell             3.0  Baratheon            Bolton

### Ejercicio 5

Añadid una nueva columna al _dataframe_ con un valor booleano indicando una predicción básica de si en una cierta batalla el bando atacante será vencedor. Definiremos el valor como _True_ sí el bando atacante es mayor al defensor, y como _False_ en caso contrario. Definid como _NaN_ aquellos casos en los que no haya número de tropas en ningún bando. ¿En que casos, identificados por el número de batalla (*battle\_number*), nuestra predicción coincide con el resultado real?

In [111]:
# Respuesta

# aqui no supe como hacer con list comprenhension ni con np.where, he encontrado este metodo mas complejo y mas descriptivo a la vez

import numpy as np
conditions = [
    (df['attacker_size'] > df['defender_size']),
    (df['attacker_size'] < df['defender_size'])]
choices = [True, False]
df['prediction'] = np.select(conditions, choices, default='NaN')

conditions2 = [
    ((df['prediction'] == True) & (df['attacker_outcome'] == 'win')),
    ((df['prediction'] == True) & (df['attacker_outcome'] == 'loss')),
    ((df['prediction'] == False) & (df['attacker_outcome'] == 'loss')),
    ((df['prediction'] == False) & (df['attacker_outcome'] == 'win'))]
choices2 = [True, False, True, False]
df['succesful_prediction'] = np.select(conditions, choices, default='NaN')

df['succesful_prediction'].value_counts()

NaN      24
False     8
True      6
Name: succesful_prediction, dtype: int64